f=open('30 days 30 hours operations.txt','w')
str=input('Enter text:')
f.write(str)
f.close()
f=open('30 days 30 hours operations','r')
print("the file contents are :")
str=f.read()
print(str)
f.close()
